[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: UI tests
    api: API tests
    smoke: Smoke tests
addopts = -v -s --strict-markers
